export const ADD_INGREDIANT='ADD_INGREDIANT'
export const REMOVE_INGREDIANT='REMOVE_INGREDIANT'
export const UPDATE_ADD='UPDATE_ADD'
export const UPDATE_REMOVE='UPDATE_REMOVE'
export const CHECK_TOTAL = 'CHECK_TOTAL'
export const SET_INGREDIENTS='SET_INGREDIENTS'
export const SET_INGREDIENTS_FAIL='SET_INGREDIENTS_FAIL'


export const SEND_ORDERS='SEND_ORDERS'
export const SEND_ORDERS_FAIL='SEND_ORDERS_FAIL'
export const UPDATE_LOADING='UPDATE_LOADING'
export const PURCHANSING_SUCCESS='PURCHANSING_SUCCESS'

export const GET_ORDERS_FAIL='GET_ORDERS_FAIL'
export const GET_ORDERS_SUCCESS='GET_ORDERS_SUCCESS'
export const UPDATE_ORDER_LOADING='UPDATE_ORDER_LOADING'


export const SIGNUP_FAIL='SIGNUP_FAIL'
export const SIGNUP_SUCCESS='SIGNUP_SUCCESS'
export const SIGNUP_LOADING='SIGNUP_LOADING'
export const AUTH_LOGOUT='AUTH_LOGOUT'
